#!/sbin/runscript
# $Header: /var/cvsroot/gentoo-x86/dev-db/redis/files/redis.initd,v 1.4 2012/02/04 21:17:55 swegener Exp $

REDIS_DIR=${REDIS_DIR:-/var/lib/redis}
REDIS_CONF=${REDIS_CONF:-/etc/redis.conf}
REDIS_OPTS=${REDIS_OPTS:-"${REDIS_CONF}"}
REDIS_USER=${REDIS_USER:-redis}
REDIS_GROUP=${REDIS_GROUP:-redis}

command=/usr/sbin/redis-server
start_stop_daemon_args="--chdir \"${REDIS_DIR}\"
	--user ${REDIS_USER} --group ${REDIS_GROUP}"
command_args="${REDIS_OPTS}"
pidfile=${REDIS_PID:-/var/run/redis/redis.pid}

depend() {
	use net localmount logger
	after keepalived
}

start_pre() {
	checkpath -d -m 0775 -o ${REDIS_USER}:${REDIS_GROUP} $(dirname ${REDIS_PID})
}
